[tool.poetry]
name = "task1"
version = "0.1.0"
description = ""
authors = ["yhyun"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"
jira = "^3.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
